spring.application.name=mcpulsor-host

# Ollama model that doesn't support tools
#spring.ai.ollama.chat.model=gemma3:4b-it-q4_K_M

# Ollama model that supports tools
spring.ai.ollama.chat.model=PetrosStav/gemma3-tools:4b

spring.ai.ollama.base-url=http://localhost:11434

spring.ai.mcp.client.name=mcpulsor-client
spring.ai.mcp.client.version=1.0.0
spring.ai.mcp.client.type=sync
spring.ai.mcp.client.streamable-http.connections.mcpulsor-server.url=http://localhost:8091
spring.ai.mcp.client.streamable-http.connections.mcpulsor-server.endpoint=/mcpulsor